name: Laravel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: catalogo_finanzas
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar PHP y extensiones
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo, pdo_pgsql, intl

    - name: Instalar Composer
      run: composer install --no-progress --prefer-dist

    - name: Copiar .env de ejemplo
      run: cp .env.example .env

    - name: Generar clave de app
      run: php artisan key:generate

    - name: Correr migraciones
      env:
        DB_CONNECTION: pgsql
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: catalogo_finanzas
        DB_USERNAME: postgres
        DB_PASSWORD: admin
      run: php artisan migrate --force

    - name: Ejecutar tests
      run: php artisan test
